services:
  api-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"

volumes:
  go-cache:
