// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUptimeSummary = `-- name: GetUptimeSummary :many
SELECT
    t.id,
    t.name,
    t.url,
    COUNT(cr.id) AS total_checks,
    COUNT(cr.id) FILTER (WHERE cr.is_healthy = true) AS healthy_checks,
    CASE
        WHEN COUNT(cr.id) > 0
        THEN ROUND((COUNT(cr.id) FILTER (WHERE cr.is_healthy = true))::numeric / COUNT(cr.id) * 100, 2)
        ELSE 0
    END AS uptime_percentage,
    MAX(cr.checked_at) AS last_checked_at
FROM targets t
LEFT JOIN check_results cr ON cr.target_id = t.id AND cr.checked_at >= now() - make_interval(hours => $1::int)
WHERE t.deleted_at IS NULL AND t.is_active = true
GROUP BY t.id, t.name, t.url
ORDER BY t.name
`

type GetUptimeSummaryRow struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Url              string      `json:"url"`
	TotalChecks      int64       `json:"total_checks"`
	HealthyChecks    int64       `json:"healthy_checks"`
	UptimePercentage int32       `json:"uptime_percentage"`
	LastCheckedAt    interface{} `json:"last_checked_at"`
}

func (q *Queries) GetUptimeSummary(ctx context.Context, hours int32) ([]GetUptimeSummaryRow, error) {
	rows, err := q.db.Query(ctx, getUptimeSummary, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUptimeSummaryRow{}
	for rows.Next() {
		var i GetUptimeSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.TotalChecks,
			&i.HealthyChecks,
			&i.UptimePercentage,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCheckResult = `-- name: InsertCheckResult :one
INSERT INTO check_results (target_id, status_code, response_time_ms, is_healthy, error_message, response_body, response_headers)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_id, status_code, response_time_ms, is_healthy, error_message, response_body, response_headers, checked_at
`

type InsertCheckResultParams struct {
	TargetID        pgtype.UUID `json:"target_id"`
	StatusCode      pgtype.Int4 `json:"status_code"`
	ResponseTimeMs  int32       `json:"response_time_ms"`
	IsHealthy       bool        `json:"is_healthy"`
	ErrorMessage    pgtype.Text `json:"error_message"`
	ResponseBody    pgtype.Text `json:"response_body"`
	ResponseHeaders []byte      `json:"response_headers"`
}

func (q *Queries) InsertCheckResult(ctx context.Context, arg InsertCheckResultParams) (CheckResult, error) {
	row := q.db.QueryRow(ctx, insertCheckResult,
		arg.TargetID,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.IsHealthy,
		arg.ErrorMessage,
		arg.ResponseBody,
		arg.ResponseHeaders,
	)
	var i CheckResult
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.IsHealthy,
		&i.ErrorMessage,
		&i.ResponseBody,
		&i.ResponseHeaders,
		&i.CheckedAt,
	)
	return i, err
}
