// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (name, url, method, interval_seconds, timeout_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, method, interval_seconds, timeout_seconds, is_active, created_at, deleted_at
`

type CreateTargetParams struct {
	Name            string `json:"name"`
	Url             string `json:"url"`
	Method          string `json:"method"`
	IntervalSeconds int32  `json:"interval_seconds"`
	TimeoutSeconds  int32  `json:"timeout_seconds"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTargetByID = `-- name: GetTargetByID :one
SELECT id, name, url, method, interval_seconds, timeout_seconds, is_active, created_at, deleted_at FROM targets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTargetByID(ctx context.Context, id pgtype.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByID, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTargets = `-- name: ListTargets :many
SELECT id, name, url, method, interval_seconds, timeout_seconds, is_active, created_at, deleted_at FROM targets
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.Query(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Target{}
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTarget = `-- name: SoftDeleteTarget :exec
UPDATE targets
SET deleted_at = now(), is_active = false
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTarget, id)
	return err
}
